baseURL = 'https://mesnaround.github.io/'
languageCode = 'en-us'
title = 'Plugged in and About'
theme = "hugo-theme-console"

[[module.imports]]
  path = "github.com/mrmierzejewski/hugo-theme-console"

[params]
  description = "Mark Schott's Corner of the WWW"
  animateStyle = "animate-fade-up" # Animation style for content

[[params.navlinks]]
  name = "About"
  url = "/about/"

[[params.navlinks]]
  name = "Posts"
  url = "/posts/"

[[params.navlinks]]
  name = "Photos"
  url = "/photos/"